"""change user model

Revision ID: 749ba4e6bfc6
Revises: 015b4749d670
Create Date: 2024-05-15 13:20:05.111747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '749ba4e6bfc6'
down_revision: Union[str, None] = '015b4749d670'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'zoo_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'zoo_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
