"""Remove max_daily_checkout_hours from Animal model

Revision ID: 8484acd9b492
Revises: 9a2f48b247b8
Create Date: 2025-04-18 12:39:13.345794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8484acd9b492'
down_revision: Union[str, None] = '9a2f48b247b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('animal', 'max_daily_checkout_hours', 
                   existing_type=sa.INTEGER(), 
                   nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('animal', 'max_daily_checkout_hours', 
                   existing_type=sa.INTEGER(), 
                   nullable=False)
    # ### end Alembic commands ###
