"""add more field in animal table

Revision ID: 8ce76b898864
Revises: a62073cdea72
Create Date: 2024-05-15 17:12:28.737695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8ce76b898864'
down_revision: Union[str, None] = 'a62073cdea72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('animal', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('animal', sa.Column('daily_checkout_count', sa.Integer(), nullable=False))
    op.add_column('animal', sa.Column('daily_checkout_duration', sa.Interval(), nullable=False))
    op.add_column('animal', sa.Column('last_checkin_time', sa.DateTime(), nullable=True))
    op.add_column('animal', sa.Column('checked_in', sa.Boolean(), nullable=False))
    op.add_column('animal', sa.Column('handling_enabled', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('animal', 'handling_enabled')
    op.drop_column('animal', 'checked_in')
    op.drop_column('animal', 'last_checkin_time')
    op.drop_column('animal', 'daily_checkout_duration')
    op.drop_column('animal', 'daily_checkout_count')
    op.drop_column('animal', 'description')
    # ### end Alembic commands ###
