"""Rename Animal.image to image_filename

Revision ID: 9a2f48b247b8
Revises: 03f99d856185
Create Date: 2025-04-18 11:57:23.127911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9a2f48b247b8'
down_revision: Union[str, None] = '03f99d856185'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('animal', sa.Column('image_filename', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # op.drop_column('animal', 'image')
    op.alter_column('animal', 'image', new_column_name='image_filename', existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('animal', sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=True))
    # op.drop_column('animal', 'image_filename')
    op.alter_column('animal', 'image_filename', new_column_name='image', existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###
