"""fix many to many models

Revision ID: fba306ed119e
Revises: c7819aff687c
Create Date: 2024-05-17 22:04:05.125481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'fba306ed119e'
down_revision: Union[str, None] = 'c7819aff687c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('animal_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('user_in_id', sa.Integer(), nullable=True),
    sa.Column('user_out_id', sa.Integer(), nullable=True),
    sa.Column('checked_in', sa.DateTime(), nullable=True),
    sa.Column('checked_out', sa.DateTime(), nullable=True),
    sa.Column('duration', sa.Interval(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['animal_id'], ['animal.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['user_in_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_out_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('animalevent')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('animalevent',
    sa.Column('animal_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('event_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['animal_id'], ['animal.id'], name='animalevent_ibfk_1'),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], name='animalevent_ibfk_2'),
    sa.PrimaryKeyConstraint('animal_id', 'event_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('animal_event')
    # ### end Alembic commands ###
