"""add tiers to animal and user table

Revision ID: ff312febc602
Revises: fba306ed119e
Create Date: 2024-05-18 11:10:15.680763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ff312febc602'
down_revision: Union[str, None] = 'fba306ed119e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('animal', sa.Column('tier', sa.Integer(), nullable=False))
    op.add_column('user', sa.Column('tier', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'tier')
    op.drop_column('animal', 'tier')
    # ### end Alembic commands ###
